name: RedeemMe
main: to.joe.redeem.RedeemMe
version: '${project.version}'
website: http://joe.to
author: Eviltechie
description: Delivers items
softdepend: [Vault, StrangeWeapons]
commands:
  redeem:
    description: Redeem items or coupons
    usage: /<command>
    permission: redeem.redeem
    permission-message: No soup for you
  printcoupon:
    description: Turn a coupon code into physical item
    usage: /<command> <code>
    permission: redeem.printcoupon
    permission-message: You may not print coupons
  createpackage:
    description: Create a package for redemption
    usage: /<command>
    permission: redeem.createpackage
    permission-message: You may not create packages
    aliases: [newpackage]
permissions:
  redeem.redeem:
    description: Redeem packages or coupons
    default: true
  redeem.createpackage:
    description: Create packages for redemption
  redeem.createpackage.*:
    description: All permissions for creating packages
    children:
      redeem.createpackage: true
      redeem.createpackage.money: true
      redeem.createpackage.item: true
      redeem.createpackage.command: true
  redeem.createpackage.money:
    description: Allows adding money to packages
    children:
      redeem.createpackage: true
  redeem.createpackage.item:
    description: Allows adding items to packages
    children:
      redeem.createpackage: true
  redeem.createpackage.command:
    description: Allows adding commands to packages
    children:
      redeem.createpackage: true