name: RedeemMe
main: to.joe.redeem.RedeemMe
version: '${project.version}'
website: http://joe.to
author: Eviltechie
description: Delivers items
softdepend: [Vault, StrangeWeapons]
commands:
  redeem:
    description: Redeem items or coupons
    usage: /redeem
    permission: redeem.redeem
    permission-message: No soup for you
  printcoupon:
    usage: /printcoupon
  rdtest:
    usage: /<command>
  createpackage:
    description: Create a package for redemption
    usage: /<command>
    permission: redeem.createpackage
    permission-message: You may not create packages
permissions:
  redeem.redeem:
    description: Redeem packages or coupons
    default: true
  redeem.createpackage:
    description: Create packages for redemption